# List of all variables
variables = [
    "INPUTFOLDER", "OUTPUTFOLDER", "PARAMFOLDER", "DIMFOLDER",
    "SKIMTIME", "SKIMDISTANCE",
    "LINKS", "NODES",
    "EMISSIONFACS",
    "EMISSIONFACS_BUITENWEG_LEEG", "EMISSIONFACS_BUITENWEG_VOL",
    "EMISSIONFACS_SNELWEG_LEEG", "EMISSIONFACS_SNELWEG_VOL",
    "EMISSIONFACS_STAD_LEEG", "EMISSIONFACS_STAD_VOL",
    "ZONES", "SEGS", "SUP_COORDINATES_ID",
    "DISTRIBUTIECENTRA", "DC_OPP_NUTS3",
    "NSTR_TO_LS",
    "MAKE_DISTRIBUTION", "USE_DISTRIBUTION",
    "DEPTIME_FREIGHT", "DEPTIME_PARCELS",
    "FIRMSIZE", "SBI_TO_SEGS",
    "COST_VEHTYPE", "COST_SOURCING",
    "COMMODITYMATRIX",
    "PARCELNODES", "CEP_SHARES",
    "MRDH_TO_NUTS3", "NUTS3_TO_MRDH", "MRDH_TO_COROP",
    "VEHICLE_CAPACITY",
    "LOGISTIC_FLOWTYPES",
    "PARAMS_SIF_PROD", "PARAMS_SIF_ATTR",
    "PARAMS_TOD", "PARAMS_SSVT",
    "PARAMS_ET_FIRST", "PARAMS_ET_LATER",
    "PARAMS_ECOMMERCE",
    "FREIGHT_DISTANCEDECAY",
    "SERVICE_DISTANCEDECAY", "SERVICE_PA",
    "PARCELS_PER_HH", "PARCELS_PER_EMPL",
    "PARCELS_MAXLOAD", "PARCELS_DROPTIME",
    "PARCELS_SUCCESS_B2C", "PARCELS_SUCCESS_B2B",
    "PARCELS_GROWTHFREIGHT",
    "CROWDSHIPPING",
    "CRW_PARCELSHARE", "CRW_MODEPARAMS",
    "CRW_PDEMAND_CAR", "CRW_PDEMAND_BIKE",
    "ZEZ_CONSOLIDATION", "ZEZ_SCENARIO",
    "NEAREST_DC",
    "NUTSLEVEL_INPUT",
    "YEARFACTOR",
    "IMPEDANCE_SPEED_FREIGHT", "IMPEDANCE_SPEED_VAN",
    "N_CPU", "N_MULTIROUTE",
    "SHIPMENTS_REF", "FIRMS_REF",
    "SELECTED_LINKS",
    "CORRECTIONS_TONNES",
    "MICROHUBS", "VEHICLETYPES",
    "FAC_LS0", "FAC_LS1", "FAC_LS2", "FAC_LS3",
    "FAC_LS4", "FAC_LS5", "FAC_LS6", "FAC_LS7",
    "SHIFT_FREIGHT_TO_COMB1", "SHIFT_VAN_TO_COMB1",
    "SHIFT_FREIGHT_TO_COMB2",
    "SEEDS",
    "LABEL",
    "MODULES"]

# Which variables are of numeric nature
numeric = [
    "PARCELS_PER_HH", "PARCELS_PER_EMPL",
    "PARCELS_MAXLOAD", "PARCELS_DROPTIME",
    "PARCELS_SUCCESS_B2C", "PARCELS_SUCCESS_B2B",
    "PARCELS_GROWTHFREIGHT",
    "YEARFACTOR",
    "NUTSLEVEL_INPUT",
    "CRW_PARCELSHARE",
    "N_MULTIROUTE",
    "FAC_LS0", "FAC_LS1", "FAC_LS2", "FAC_LS3",
    "FAC_LS4", "FAC_LS5", "FAC_LS6", "FAC_LS7",
    "SHIFT_FREIGHT_TO_COMB1", "SHIFT_VAN_TO_COMB1",
    "SHIFT_FREIGHT_TO_COMB2"]

# Which variables refer to a directory path
directories = [
    "INPUTFOLDER",
    "OUTPUTFOLDER",
    "PARAMFOLDER",
    "DIMFOLDER"]

# Which variables refer to the modules that need to be run
modules = [
    "MODULES"]

# Which variables refer to a file path
files = [
    "SKIMTIME", "SKIMDISTANCE",
    "LINKS", "NODES",
    "EMISSIONFACS",
    "EMISSIONFACS_BUITENWEG_LEEG", "EMISSIONFACS_BUITENWEG_VOL",
    "EMISSIONFACS_SNELWEG_LEEG", "EMISSIONFACS_SNELWEG_VOL",
    "EMISSIONFACS_STAD_LEEG", "EMISSIONFACS_STAD_VOL",
    "ZONES", "SEGS", "SUP_COORDINATES_ID",
    "DISTRIBUTIECENTRA", "DC_OPP_NUTS3",
    "NSTR_TO_LS",
    "MAKE_DISTRIBUTION", "USE_DISTRIBUTION",
    "DEPTIME_FREIGHT", "DEPTIME_PARCELS",
    "FIRMSIZE", "SBI_TO_SEGS",
    "COST_VEHTYPE", "COST_SOURCING",
    "COMMODITYMATRIX",
    "PARCELNODES", "CEP_SHARES",
    "MRDH_TO_NUTS3", "NUTS3_TO_MRDH", "MRDH_TO_COROP",
    "VEHICLE_CAPACITY",
    "LOGISTIC_FLOWTYPES",
    "PARAMS_SIF_PROD", "PARAMS_SIF_ATTR",
    "PARAMS_TOD", "PARAMS_SSVT",
    "PARAMS_ET_FIRST", "PARAMS_ET_LATER",
    "PARAMS_ECOMMERCE",
    "FREIGHT_DISTANCEDECAY",
    "SERVICE_DISTANCEDECAY", "SERVICE_PA",
    "ZEZ_CONSOLIDATION", "ZEZ_SCENARIO",
    "SHIPMENTS_REF", "FIRMS_REF",
    "CORRECTIONS_TONNES",
    "CRW_MODEPARAMS", "CRW_PDEMAND_CAR", "CRW_PDEMAND_BIKE",
    "MICROHUBS", "VEHICLETYPES",
    "SEEDS"]

# Variables that became obsolete due to changes in the modules.
# Keep these in here to prevent errors on older ini files with these
# arguments still in there.
obsolete = [
    "DEPTIME_FREIGHT",
    "PARCELS_PER_HH",
    "EMISSIONFACS_BUITENWEG_LEEG", "EMISSIONFACS_BUITENWEG_VOL",
    "EMISSIONFACS_SNELWEG_LEEG", "EMISSIONFACS_SNELWEG_VOL",
    "EMISSIONFACS_STAD_LEEG", "EMISSIONFACS_STAD_VOL"]

# Variables for which a value in the control file is not obligatory
optional = obsolete + [
    "SHIPMENTS_REF", "FIRMS_REF",
    "CORRECTIONS_TONNES",
    "SELECTED_LINKS",
    "N_CPU",
    "N_MULTIROUTE",
    "CROWDSHIPPING",
    "NEAREST_DC",
    "CRW_PARCELSHARE", "CRW_MODEPARAMS",
    "CRW_PDEMAND_CAR", "CRW_PDEMAND_BIKE",
    "MICROHUBS", "VEHICLETYPES",
    "FAC_LS0", "FAC_LS1", "FAC_LS2", "FAC_LS3",
    "FAC_LS4", "FAC_LS5", "FAC_LS6", "FAC_LS7",
    "SHIFT_FREIGHT_TO_COMB1", "SHIFT_VAN_TO_COMB1",
    "SHIFT_FREIGHT_TO_COMB2"]
